
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * tictac.java
 *
 * Created on 19 Jul, 2013, 8:07:27 PM
 */

/**
 *
 * @author Owner
 */
public class tictac extends javax.swing.JFrame {
   int i,j,v;
       int a[]=new int[9];
    volatile int  chance=0;
    /** Creates new form tictac */
    public tictac() {
        for(i=0;i<9;i++)
        {
            a[i]=(i*10)+1;
        }
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        t1 = new javax.swing.JLabel();
        t3 = new javax.swing.JLabel();
        t4 = new javax.swing.JLabel();
        t5 = new javax.swing.JLabel();
        t6 = new javax.swing.JLabel();
        t7 = new javax.swing.JLabel();
        t8 = new javax.swing.JLabel();
        t9 = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        ans = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        t1.setBackground(new java.awt.Color(255, 255, 255));
        t1.setOpaque(true);

        t3.setBackground(new java.awt.Color(255, 255, 255));
        t3.setOpaque(true);

        t4.setBackground(new java.awt.Color(255, 255, 255));
        t4.setOpaque(true);

        t5.setBackground(new java.awt.Color(255, 255, 255));
        t5.setOpaque(true);

        t6.setBackground(new java.awt.Color(255, 255, 255));
        t6.setText("jLabel6");
        t6.setOpaque(true);

        t7.setBackground(new java.awt.Color(255, 255, 255));
        t7.setText("jLabel7");
        t7.setOpaque(true);

        t8.setBackground(new java.awt.Color(255, 255, 255));
        t8.setText("jLabel8");
        t8.setOpaque(true);

        t9.setBackground(new java.awt.Color(255, 255, 255));
        t9.setText("jLabel9");
        t9.setOpaque(true);

        t2.setBackground(new java.awt.Color(255, 255, 255));
        t2.setOpaque(true);

        b1.setText("go");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        ans.setText("ans");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(t4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(t1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                            .addComponent(t7, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(t5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                    .addComponent(t2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t6, 0, 0, Short.MAX_VALUE)
                                    .addComponent(t3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t9)
                                .addGap(5, 5, 5)))))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1))
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(ans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(387, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(t3, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(t2, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(t1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(t6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t4, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(t8)
                        .addComponent(t9)))
                .addGap(62, 62, 62)
                .addComponent(ans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(b1)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
       int op=-1;
       int flag=0,stat=-1,stat1=-1,stat2=-1,stat3=-1,stat4=-1,stat5=-1,stat6=-1,stat7=-1;
        v=Integer.parseInt(a1.getText());
       if(chance<=9)
       {
           switch(v)
           {
               case 1:
                   t1.setText(""+chance%2);
                   break;
               case 2:
                   t2.setText(""+chance%2);
                   break;
               case 3:
                   t3.setText(""+chance%2);
                                 break;
               case 4:
                   t4.setText(""+chance%2);
                                break;
               case 5:
                   t5.setText(""+chance%2);
                                 break;
               case 6:
                   t6.setText(""+chance%2);
                                  break;
               case 7:
                   t7.setText(""+chance%2);
                                  break;
               case 8:
                   t8.setText(""+chance%2);
                   break;
               case 9:
                   t9.setText(""+chance%2);
                   break;

           }
           if(chance%2==0)
            {
               a[v-1]=0;
            }else
            {
               a[v-1]=1;
            }
       chance++;
       }

       for(i=0;i<3;i++)
       {
           for(j=0;j<3;j++)
           {
               if(i==j)
               {
                   if(flag==0)
                   {
                        op=a[i*3+j];
                        flag=1;
                   }
                   else
                   {
                        if(a[i*3+j]!=op)
                        {
                          stat=1;
                        }
                   }
               }
           }
       }
        if(stat==-1)
        {
            JOptionPane.showMessageDialog(null, "1hurry  "+op +" won");
        }
        flag=0;

        for(i=0;i<3;i++)
       {
           for(j=0;j<3;j++)
           {
               if(i+j==2)
               {
                   if(flag==0)
                   {
                        op=a[i*3+j];
                        flag=1;
                   }
                   else
                   {
                        if(a[i*3+j]!=op)
                        {
                          stat1=1;
                        }
                   }
               }
           }
       }
        if(stat1==-1)
        {
            JOptionPane.showMessageDialog(null, "2hurry "+op +"won");
        }

flag=0;
        for(i=0;i<3;i++)
       {
                   if(flag==0)
                   {
                        op=a[i];
                        flag=1;
                   }
                   else
                   {
                        if(a[i]!=op)
                        {
                          stat2=1;
                        }
                   }
               
           
       }
        if(stat2==-1)
        {
            JOptionPane.showMessageDialog(null, "3hurry "+op +"won");
        }


        
        for(i=3;i<6;i++)
       {
                   if(flag==0)
                   {
                        op=a[i];
                        flag=1;
                   }
                   else
                   {
                        if(a[i]!=op)
                        {
                          stat3=1;
                        }
                   }
               
           
       }
        if(stat3==-1)
        {
            JOptionPane.showMessageDialog(null, "4hurry "+op +"won");
        }

        for(i=6;i<9;i++)
       {
                   if(flag==0)
                   {
                        op=a[i];
                        flag=1;
                   }
                   else
                   {
                        if(a[i]!=op)
                        {
                          stat4=1;
                        }
                   }


       }
        if(stat4==-1)
        {
            JOptionPane.showMessageDialog(null, "5hurry "+op +"won");
        }
        flag=0;
        op=a[0];
                        if(a[0]!=op||a[3]!=op||a[6]!=op)
                        {
                          stat5=1;
                        }
        
        if(stat5==-1)
        {
           JOptionPane.showMessageDialog(null, "6hurry "+op +"won");
       }
       op=a[1]; 
                        if(a[1]!=op||a[4]!=op||a[7]!=op)
                        {
                          stat6=1;
                        }
        
        if(stat6==-1)
        {
           JOptionPane.showMessageDialog(null, "7hurry "+op +"won");
       }
        op=a[2];
                        if(a[2]!=op||a[5]!=op||a[9]==op)
                        {
                          stat7=1;
                        }
        
        if(stat7==-1)
        {
           JOptionPane.showMessageDialog(null, "8hurry "+op +"won");
       }
    }//GEN-LAST:event_b1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tictac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JTextField ans;
    private javax.swing.JButton b1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t3;
    private javax.swing.JLabel t4;
    private javax.swing.JLabel t5;
    private javax.swing.JLabel t6;
    private javax.swing.JLabel t7;
    private javax.swing.JLabel t8;
    private javax.swing.JLabel t9;
    // End of variables declaration//GEN-END:variables

}
